# Generated by Django 4.2.8 on 2025-12-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('skipped_tests', models.IntegerField(default=0)),
                ('run_date', models.DateField()),
                ('allure_report_url', models.URLField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='reports.build')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('execution_date', models.DateField()),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='reports.testrun')),
            ],
        ),
    ]
