# Generated by Django 5.1.14 on 2025-12-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_type', models.CharField(db_index=True, default='Other', max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=50)),
                ('run_date', models.DateField()),
                ('allure_report_url', models.URLField()),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('skipped_tests', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='reports.build')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('execution_date', models.DateField()),
                ('architecture', models.CharField(default='Other', max_length=50)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='reports.testrun')),
            ],
        ),
    ]
