# Generated by Django 5.1.14 on 2025-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
