# Generated by Django 5.1.14 on 2025-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_uuid_to_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_number',
            field=models.CharField(max_length=50),
        ),
    ]
