# Generated by Django 5.1.14 on 2025-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_uniqe_from_build_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
