# Generated by Django 5.1.14 on 2025-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_null_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='run_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
